# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-cache_by_page-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew vonderLuft"]
  s.date = %q{2011-05-09}
  s.description = %q{Enables per page admin option of setting caching to a non-default value, or turning it off altogether.}
  s.email = %q{avonderluft@avlux.net}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "HELP_admin.textile",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/views/admin/pages/_caching_meta.html.haml",
    "app/views/admin/pages/_caching_td.html.haml",
    "app/views/admin/pages/_caching_th.html.haml",
    "cache_by_page_extension.rb",
    "db/migrate/001_add_page_options.rb",
    "lib/cache_by_page/page_extensions.rb",
    "lib/cache_by_page/site_controller_extensions.rb",
    "lib/tasks/cache_by_page_extension_tasks.rake",
    "radiant-cache_by_page-extension.gemspec",
    "spec/controllers/admin_pages_controller_spec.rb",
    "spec/controllers/site_controller_extensions_spec.rb",
    "spec/integration/page_caching_spec.rb",
    "spec/models/page_extensions_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/avonderluft/radiant-cache_by_page-extension}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Cache By Page Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin_pages_controller_spec.rb",
    "spec/controllers/site_controller_extensions_spec.rb",
    "spec/integration/page_caching_spec.rb",
    "spec/models/page_extensions_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.1"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.1"])
  end
end

